brainforce/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from brainforce.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('quiz.urls', namespace='brainiac', app_name='quiz')),
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': MEDIA_ROOT}),
]

quiz/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^about/', views.view_about, name='about'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^$', views.view_index, name='index')
]

quiz/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
import time


class UserStat:
    def __init__(self, usr):
        self.user = usr
        try:
            self.social = usr.social_auth.get(provider='vk-oauth2')
        except:
            pass
        self.stat = Answer.objects.filter(user=usr, correct=True).aggregate(
            question_points=models.Sum('question__value'),
            bonus_points=models.Sum('bonus'),
            count=models.Count('*'),
        )
        self.total = self.get_total()
        self.bonus = self.get_bonus_points()
        self.points = self.get_question_points()
        self.count = self.get_count()

    def get_total(self):
        try:
            return self.get_bonus_points() + self.get_question_points()
        except TypeError:
            return 0

    def get_count(self):
        return self.stat['count'] if self.stat['count'] is not None else 0

    def get_bonus_points(self):
        return self.stat['bonus_points'] if self.stat['bonus_points'] is not None else 0

    def get_question_points(self):
        return self.stat['question_points'] if self.stat['question_points'] is not None else 0


class Question(models.Model):
    text = models.TextField()
    suggestedAnswer = models.TextField()
    pic = models.ImageField(blank=True)
    value = models.PositiveSmallIntegerField()
    date = models.DateField(unique=True)

    def __str__(self):
        return "Question for {date}".format(date=self.date)

    @staticmethod
    def get_current_question():
        now = datetime.fromtimestamp(time.time())
        if now.hour < 18:
            return Question.objects.get(date=(now - timedelta(days=1)).date())

        return Question.objects.get(date=now.date())


class Answer(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField()
    question = models.ForeignKey(Question)
    time = models.DateTimeField(auto_created=True, auto_now_add=True)
    correct = models.NullBooleanField(null=True)
    bonus = models.PositiveSmallIntegerField(null=True,
                                             default=0)

    def __str__(self):
        return "{user}'s answer ({question})".format(user=self.user, question=self.question)

quiz/forms.py
# -*- coding: utf-8 -*-

from django import forms
from quiz.models import Answer


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text',)

quiz/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.db.models import Sum, Count
from django.contrib.auth.models import User
from datetime import datetime
from quiz.forms import AnswerForm
import time
from .models import Answer, Question, UserStat


def view_about(request):
    if request.user.is_authenticated():
        social = request.user.social_auth.get(provider='vk-oauth2')
        return render(request, 'quiz/about.html', {
            'first_name': social.extra_data['first_name'],
            'last_name': social.extra_data['last_name']
        })
    return render(request, 'quiz/about.html')


def view_management(request):
    if request.method == "POST":
        answer = Answer.objects.get(pk=request.POST['answer'])
        answer.correct = request.POST['is_right'].lower() == "true"

        if len(Answer.objects.filter(question=answer.question, correct=True)) < 20 and answer.correct:
            answer.bonus = 5

        answer.save()

        return redirect('/')

    try:
        answer = Answer.objects.filter(correct=None)[0]
        social = answer.user.social_auth.get(provider='vk-oauth2')
        return render(request, 'quiz/management/index.html', {
            'answer': answer,
            'first_name': social.extra_data['first_name'],
            'last_name': social.extra_data['last_name'],
            'uid': social.uid,
        })

    except (Answer.DoesNotExist, KeyError, IndexError):
        questions = Question.objects.all().order_by('date')

        question_data = []
        users = []

        for question in questions:
            answers = Answer.objects.filter(question=question, bonus__gt=0).order_by('pk')
            question_data.append((question, answers,))

        for user in User.objects.filter(is_staff=False, is_superuser=False):
            stat = UserStat(user)
            users.append(stat)

        users.sort(key=lambda x: x.get_total(), reverse=True)

        return render(request, 'quiz/management/stats.html', {
            'questions': question_data,
            'users': users,
        })


def view_index(request):
    brainiac_start_date = datetime.strptime('2016-04-20 18:00', '%Y-%m-%d %H:%M')
    now = datetime.fromtimestamp(time.time())
    time_delta = brainiac_start_date - now
    if request.user.is_staff:
        return view_management(request)
    try:
        question = Question.get_current_question()
        if not request.user.is_authenticated():
            return render(request, 'quiz/index_question_guest.html', {'question': question})

        social = request.user.social_auth.get(provider='vk-oauth2')

        try:
            answer = Answer.objects.get(question=question, user=request.user)

            return render(request, 'quiz/index_question_answered.html', {
                'question': question,
                'first_name': social.extra_data['first_name'],
                'last_name': social.extra_data['last_name'],
                'answer': answer.text,
            })

        except Answer.DoesNotExist:
            pass

        if request.method == "POST":
            form = AnswerForm(request.POST)
            if form.is_valid():
                answer = Answer(user=request.user, question=question, text=form.cleaned_data['text'])
                answer.save()
                return redirect('/')
        else:
            form = AnswerForm()

        return render(request, 'quiz/index_question.html', {
            'question': question,
            'first_name': social.extra_data['first_name'],
            'last_name': social.extra_data['last_name'],
            'form': form,
        })

    except Question.DoesNotExist:
        pass

    if time_delta.days > 1:
        return render(request, 'quiz/index_not_started.html', {'time_delta': time_delta})
    elif request.user.is_authenticated():

        stat = UserStat(request.user)

        return render(request, 'quiz/index_finished.html', {
            'question_points': stat.get_question_points(),
            'bonus_points': stat.get_bonus_points(),
            'count': stat.get_count(),
            'total_points': stat.get_total(),
        })
    return render(request, 'quiz/index_finished.html')

quiz/templates/quiz/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
	Transit by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BrainForce</title>
    <link rel="icon" type="image/x-icon" href="favicon.ico"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <!--[if lte IE 8]><script src="{% static 'quiz/js//html5shiv.js' %}"></script>
    <![endif]-->
    <script src="{% static 'quiz/js/jquery.min.js' %}"></script>
    <script src="{% static 'quiz/js/skel.min.js' %}"></script>
    <script src="{% static 'quiz/js/skel-layers.min.js' %}"></script>
    <script src="{% static 'quiz/js/init.js' %}"></script>
        <link rel="stylesheet" href="{% static 'quiz/css/skel.css' %}"/>
        <link rel="stylesheet" href="{% static 'quiz/css/style.css' %}"/>
        <link rel="stylesheet"
              href="{% static 'quiz/css/style-xlarge.css' %}"/>
</head>
<body class="landing">

<!-- Header -->
<header id="header">
    <nav id="nav">
        <ul>

        </ul>
    </nav>
</header>

<!-- Banner -->
<section id="banner">
    <h2>BrainForce</h2>
    <p>Интеллектуально-развлекательная игра</p>
</section>

<!-- One -->
<section id="one" class="wrapper style1 special">
    <div class="container">
        {% block one %}
        {% endblock %}
    </div>
</section>

<!-- Two -->
{% block two %}{% endblock %}

<!-- Three -->
<section id="three" class="wrapper style3 special">
    <div class="container">
        {% block three %}
        {% endblock %}
    </div>
</section>

<!-- Footer -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="8u 12u$(medium)">
                <ul class="copyright">
                    <li>&copy; All content is licensed under CC-BY 3.0</li>
                    <li>Design: based on <a href="http://templated.co/transit">TRANSIT</a>
                        template by <a href="http://templated.co">TEMPLATED</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

quiz/templates/quiz/index__do_nachala_NOTauth.html
{% extends 'quiz/base.html' %}

<!-- One -->
{% block one %}
    <header class="major">
        <h2>Состояние конкурса:</h2>
        <p>Еще не начался</p>
    </header>
    <div class="row 150%">
        <div class="4u 12u$(medium)">
            <section class="box"><em
                    class="icon big rounded color1 fa-calendar"></em>
                <h3>Дата начала интернет-тура:</h3>
                <p>18 апреля 2016</p>
                <p>18:00</p>
            </section>
        </div>
        <div class="4u 12u$(medium)">
            <section class="box">
                <i class="icon big rounded color9 fa-sign-in"></i>
                <h3>Авторизация:</h3>
                <p>Используется авторизация через VK с последующим
                    использованием указанных Имени, Фамилии и ID.</p>
            </section>
        </div>
        <div class="4u$ 12u$(medium)">
            <section class="box">
                <i class="icon big rounded color6 fa-clock-o"></i>
                <h3>Время на ответ:</h3>
                <p>Ответить на вопрос можно в интервал с 18:00 по 18:00
                    следующего дня. В это время начинается следующий
                    вопрос.</p>
            </section>
        </div>
    </div>

{% endblock %}


{% block three %}
    <header class="major">
        <h2>Регламент и правила</h2>
    </header>
    <div class="container-white">

        <div id="content">
            <h1><a id="_0"></a>ПРАВИЛА</h1>
            <p>Конкурс состоит из двух частей:</p>
            <ol>
                <li>Отборочный Интернет-тур</li>
                <li>Очная часть</li>
            </ol>
            <p>Интернет-тур проходит с помощью специально созданного сайта, на
                котором отображается место каждого участника в рейтинговом
                списке. В рамках Интернет-тура участникам предлагается ответить
                на один вопрос в специально отведенной для этого теме.</p>
            <ul>
                <li>Новый вопрос открывается <strong>каждый день</strong> на
                    сайте конкурса <a href="http://fbmiet.ru">www.fbmiet.ru</a>
                    в одно и то же время <strong>(в 18:00)</strong>.
                </li>
                <li>Ответы принимаются в течение <em><strong>24 часов</strong></em>
                    после публикации вопроса <strong>(до 18:00 следующего
                        дня)</strong>.
                </li>
            </ul>
            <h4><a id="__10"></a>Заочная часть</h4>
            <p>В первой <strong>(заочной)</strong> части конкурса участвовать
                может любой желающий, зарегистрировавшийся на сайте конкурса.
                Но очевидно, что у участника, зарегистрировавшегося после
                начала конкурса, шансы будут на порядок ниже, так как вопросы
                прошедших дней <strong>не будут доступны для ответа</strong>.
                Участник может ответить на любое количество любых вопросов из
                предложенных.</p>
            <ul>
                <li>Максимальное количество вопросов в заочном туре -
                    <em><strong>6</strong></em>.
                </li>
                <li>За каждый правильный ответ участники будут получать
                    <em><strong>10</strong></em> баллов.
                </li>
                <li>Первые <em><strong>20</strong></em> правильно ответивших
                    получают бонус в размере <em><strong>+5</strong></em>
                    баллов.
                </li>
            </ul>
            <p>По сумме набранных баллов будет происходить отбор участников в
                очную часть. После окончания заочной части, на сайте
                Интернет-тура и в группе <a
                        href="https://vk.com/miet.brainforce">Brainforce</a>
                ВКонтакте будут опубликованы списки участников, успешно
                прошедших заочный тур и допущенных до очного тура.</p>
            <h4><a id="__18"></a>Очная часть</h4>
            <p>Вторая <strong>(очная)</strong> часть конкурса проходит
                непосредственно в здании <a href="https://miet.ru/">НИУ
                    “МИЭТ”</a>. К нему допускается установленное оргкомитетом
                количество участников Интернет-тура, которые набрали <strong>наибольшее</strong>
                количество баллов (в случае совпадения количества баллов,
                приоритет отдается тому, кто ответил <strong>быстрее</strong>)
            </p>
            <ul>
                <li>Во время очной части участникам предстоит в течение
                    определенного времени решить определенное число задач
                    различных типов.
                </li>
                <li>По прохождении последнего этапа победитель будет определен
                    по <strong>сумме баллов за все этапы <em>очной
                        части</em></strong>.
                </li>
            </ul>
            <h5><a id="_______23"></a><em><strong>Призеры будут награждены
                ценными призами!</strong></em>.</h5>

        </div>

    </div>
{% endblock %}

quiz/templates/quiz/index_finished.html
{% extends 'quiz/base.html' %}

<!-- One -->
{% block one %}
    <header class="major">
        <h2>Состояние конкурса:</h2>
        <p>Завершен заочный этап</p>
    </header>
    <div class="row 150%">
        <div class="4u 12u$(medium)">
            <section class="box"><em
                    class="icon big rounded color1 fa-exclamation"></em>
                <h3>Дата окончания:</h3>
                <p>23 апреля 2016</p>
                <p>18:00</p>
            </section>
        </div>
        <div class="4u 12u$(medium)">
            <section class="box">
                <i class="icon big rounded color9 fa-sign-in"></i>
                <h3>Авторизация:</h3>
                <p>Используется авторизация через VK с последующим
                    использованием указанных Имени, Фамилии и ID.</p>
            </section>
        </div>
        <div class="4u$ 12u$(medium)">
            <section class="box">
                <i class="icon big rounded color6 fa-clock-o"></i>
                <h3>Время на ответ:</h3>
                <p>Ответить на вопрос можно в интервал с 18:00 по 18:00
                    следующего дня. В это время начинается следующий
                    вопрос.</p>
            </section>
        </div>
    </div>
{% endblock %}
{% block two %}
    <!-- Two -->
    <section id="two" class="wrapper style2 special">
        <div class="container">
            <header class="major">
                <h2>Заочный этап завершен.</h2>

            </header>
        </div>
    </section>
{% endblock %}
{% block three %}
    <!-- Three -->
    <header class="major">
        <h2>Регламент и правила</h2>
    </header>
    <div class="container-white">

        <div id="content">
            <h1><a id="_0"></a>ПРАВИЛА</h1>
            <p>Конкурс состоит из двух частей:</p>
            <ol>
                <li>Отборочный Интернет-тур</li>
                <li>Очная часть</li>
            </ol>
            <p>Интернет-тур проходит с помощью специально созданного сайта, на
                котором отображается место каждого участника в рейтинговом
                списке. В рамках Интернет-тура участникам предлагается ответить
                на один вопрос в специально отведенной для этого теме.</p>
            <ul>
                <li>Новый вопрос открывается <strong>каждый день</strong> на
                    сайте конкурса <a href="http://fbmiet.ru">www.fbmiet.ru</a>
                    в одно и то же время <strong>(в 18:00)</strong>.
                </li>
                <li>Ответы принимаются в течение <em><strong>24 часов</strong></em>
                    после публикации вопроса <strong>(до 18:00 следующего
                        дня)</strong>.
                </li>
            </ul>
            <h4><a id="__10"></a>Заочная часть</h4>
            <p>В первой <strong>(заочной)</strong> части конкурса участвовать
                может любой желающий, зарегистрировавшийся на сайте конкурса.
                Но очевидно, что у участника, зарегистрировавшегося после
                начала конкурса, шансы будут на порядок ниже, так как вопросы
                прошедших дней <strong>не будут доступны для ответа</strong>.
                Участник может ответить на любое количество любых вопросов из
                предложенных.</p>
            <ul>
                <li>Максимальное количество вопросов в заочном туре -
                    <em><strong>6</strong></em>.
                </li>
                <li>За каждый правильный ответ участники будут получать
                    <em><strong>10</strong></em> баллов.
                </li>
                <li>Первые <em><strong>20</strong></em> правильно ответивших
                    получают бонус в размере <em><strong>+5</strong></em>
                    баллов.
                </li>
            </ul>
            <p>По сумме набранных баллов будет происходить отбор участников в
                очную часть. После окончания заочной части, на сайте
                Интернет-тура и в группе <a
                        href="https://vk.com/miet.brainforce">Brainforce</a>
                ВКонтакте будут опубликованы списки участников, успешно
                прошедших заочный тур и допущенных до очного тура.</p>
            <h4><a id="__18"></a>Очная часть</h4>
            <p>Вторая <strong>(очная)</strong> часть конкурса проходит
                непосредственно в здании <a href="https://miet.ru/">НИУ
                    “МИЭТ”</a>. К нему допускается установленное оргкомитетом
                количество участников Интернет-тура, которые набрали <strong>наибольшее</strong>
                количество баллов (в случае совпадения количества баллов,
                приоритет отдается тому, кто ответил <strong>быстрее</strong>)
            </p>
            <ul>
                <li>Во время очной части участникам предстоит в течение
                    определенного времени решить определенное число задач
                    различных типов.
                </li>
                <li>По прохождении последнего этапа победитель будет определен
                    по <strong>сумме баллов за все этапы <em>очной
                        части</em></strong>.
                </li>
            </ul>
            <h5><a id="_______23"></a><em><strong>Призеры будут награждены
                ценными призами!</strong></em>.</h5>

        </div>

    </div>
{% endblock %}

quiz/templates/quiz/management/index.html
{% extends 'quiz/management/base.html' %}
{% block content %}
    <h3>Проверка вопроса!</h3>
    {% if answer.question.pic %}
        <img src="{{ answer.question.pic.url }}" alt="question {{ answer.question.date|date }}"/>
    {% else %}
        {{ answer.question.text }}
    {% endif %}
    <h4>Правильный ответ:</h4>
    <p>
        {{ answer.question.suggestedAnswer }}
    </p>
    <h3>Ответ участника <a href="https://vk.com/id{{ uid }}">{{ first_name }} {{ last_name }}</a></h3>

    <p> {{ answer.text }}</p>

    <form action="/" method="post">

        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" name="is_right" value="true">
            Правильно
        </button>


        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" name="is_right" value="false">
            Неправильно
        </button>

        <input type="hidden" name="answer" value="{{ answer.id }}" />
    </form>

{% endblock %}

quiz/templates/quiz/management/stats.html
{% extends 'quiz/management/base.html' %}
{% block content %}
    <h3>Статистика</h3>
    <table class="mdl-data-table mdl-js-data-table">
        <thead>
        <tr>
            <th>Место</th>
            <th class="mdl-data-table__cell--non-numeric">Имя</th>
            <th>Баллы</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="https://vk.com/{{ user.user.username }}">@{{ user.user.username }} ({{ user.social.extra_data.first_name }} {{ user.social.extra_data.last_name }})</a></td>
            <td>{{ user.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h3>Статистика по дням:</h3>


    {% for i in questions %}
        {# i.0 - question, i.1 -- answers #}
        <h4>Вопрос от {{ i.0.date }}</h4>
        <h5>Текст:</h5>
        <p>{{ i.0.text }} ({{ i.0.suggestedAnswer }})</p>
        <h5>Ответы:</h5>
        <ul>
        {% for ans in i.1 %}
            <li><a href="https://vk.com/{{ ans.user.username }}">{{ ans.user.username }}</a> ({{ ans.time }})</li>
        {% endfor %}
        </ul>
    {% endfor %}

{% endblock %}

quiz/templates/quiz_old/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    {% include 'quiz/fragment_head.html' %}
</head>

<body>
<header id="header-a">
    <div id="bg-pattern">
        <div id="top-a">
            <h1 id="logo-a">ForceBrain</h1>
            <nav>
                <a href="{% url 'brainiac:index' %}">На главную</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'brainiac:logout' %}">Выйти ({{ first_name }} {{ last_name }})</a>
                {% endif %}
            </nav>
        </div>
    </div>
</header>

<div id="content">
    {% include "quiz/fragment_about.html" %}
</div>
<!-- Scripts -->
<script src="{% static 'quiz/js/maskedinput.min.js' %}"></script>
<script type="text/javascript">
    jQuery(function ($) {
        $("#phone").mask("+7 (999) 999-9999");
    });
</script>
</body>
</html>

quiz/templates/quiz_old/index_question_img_guest.html
{% extends 'quiz/question_img_base.html' %}
{% block question %}

    <h2>Что изображено на картинке?</h2>

{% endblock %}
{% block form %}
    <a class="sign-up" href="{% url 'social:begin' backend='vk-oauth2' %}">Войти и ответить</a>
{% endblock %}

quiz/templates/quiz_old/question_base.html
{% load staticfiles %}
{% load brainiac %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Захватывающая интеллектуально-развлекательная игра ForceBrain</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'quiz/css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'quiz/css/style.css'%}">
    <!-- Roboto 300,400,500 -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,300,500&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <!-- Open Sans 400,700 -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <!-- Likely -->
    <script src="{% static 'quiz/js/jquery.js'%}"></script>
    <script src="{% static 'quiz/js/likely.js'%}"></script>
    <script src="{% static 'quiz/js/popup.js'%}"></script>
    <link rel="stylesheet" href="{% static 'quiz/css/likely.css'%}">
    <!-- Фавикон -->
    <link rel="icon" type="image/png" href="{% static 'quiz/img/favicon.png'%}" />
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
<header id="header-q">
    <div id="bg-pattern">
        <div class="cont">
            <div id="text">
                <div id="top-q">
                    <h1 id="logo-q">ForceBrain</h1>
                    <nav>
                        <a href="{% url 'brainiac:about' %}">Об игре</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'brainiac:logout' %}">Выйти ({{ first_name }} {{ last_name }})</a>
                        {% endif %}
                    </nav>
                </div>

                <div class="clear-q"></div>

                <div id="middle-q">
                    {% block question %}
                    {% endblock %}
                </div>

                <div id="content-q">
                    {% block form %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <div class="foot">
            <div class="lik">
                <div class="likely likely-light">
                    <div class="twitter" data-title="BrainForce — это захватывающая интеллектуально-развлекательная игра. Сайт: fbmiet.ru">Твитнуть</div>
                    <div class="facebook" data-title="BrainForce — это захватывающая интеллектуально-развлекательная игра. Если вы хотите проверить свои силы — примите участие в заочном этапе игры с 2 по 7 ноября. fbmiet.ru">Поделиться</div>
                    <div class="vkontakte" data-title="BrainForce — это захватывающая интеллектуально-развлекательная игра. Если вы хотите проверить свои силы — примите участие в заочном этапе игры с 2 по 7 ноября. fbmiet.ru">Поделиться</div>
                </div>
            </div>
        </div>
    </div>
</header>
</body>
</html>

quiz/templates/quiz_old/question_img_base.html
{% load staticfiles %}
{% load brainiac %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Захватывающая интеллектуально-развлекательная игра ForceBrain</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'quiz/css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'quiz/css/style.css'%}">
    <!-- Roboto 300,400,500 -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,300,500&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <!-- Open Sans 400,700 -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <!-- Likely -->
    <script src="{% static 'quiz/js/jquery.js'%}"></script>
    <script src="{% static 'quiz/js/likely.js'%}"></script>
    <script src="{% static 'quiz/js/popup.js'%}"></script>
    <link rel="stylesheet" href="{% static 'quiz/css/likely.css'%}">
    <!-- Фавикон -->
    <link rel="icon" type="image/png" href="{% static 'quiz/img/favicon.png'%}" />
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
<header id="header-q">
    <div id="bg-pattern">
        <div class="cont">
            <div id="text">
                <div id="top-q">
                    <h1 id="logo-q">ForceBrain</h1>
                    <nav>
                        <a href="{% url 'brainiac:about' %}">Об игре</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'brainiac:logout' %}">Выйти ({{ first_name }} {{ last_name }})</a>
                        {% endif %}
                    </nav>
                </div>

                <div class="clear-q"></div>

                <div id="middle-q">
                    {% block question %}
                    {% endblock %}
                </div>

                <div id="content-q-i">
                    {% block form %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <div class="foot">
            <div class="lik">
                <div class="likely likely-light">
                    <div class="twitter" data-title="ForceBrain — это захватывающая интеллектуально-развлекательная игра. Сайт: fbmiet.ru">Твитнуть</div>
                    <div class="facebook" data-title="ForceBrain — это захватывающая интеллектуально-развлекательная игра. Если вы хотите проверить свои силы — примите участие в заочном этапе игры с 20 по 25 апреля. fbmiet.ru">Поделиться</div>
                    <div class="vkontakte" data-title="ForceBrain — это захватывающая интеллектуально-развлекательная игра. Если вы хотите проверить свои силы — примите участие в заочном этапе игры с 20 по 25 апреля. fbmiet.ru">Поделиться</div>
                </div>
            </div>
        </div>
    </div>
</header>
</body>
</html>